# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: hello-ingress
#   namespace: hello-namespace
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#     # - host: hello.com
#     - http:
#         paths:
#           - path: /hello
#             pathType: Prefix
#             backend:
#               service:
#                 name: hello-service
#                 port:
#                   number: 80

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
  namespace: hello-namespace
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /hello
          backend:
            serviceName: hello-service
            servicePort: 80
